// SPDX-License-Identifier: BUSL-1.1
//
// Copyright © 2025 Two Factor Authentication Service, Inc.
// Licensed under the Business Source License 1.1
// See LICENSE file for full terms

/**
* Lowercase phrases that disqualify a field found by its label from being a payment card field: gift,
* loyalty and promo cards, bank accounts, one-time codes, identity documents, phone numbers and birth
* dates reuse the same "card number"/"security code" wording (e.g. "Gift card number", "Enter the security
* code sent by SMS", "Cardholder birthdate (YYMMDD)"). Matched like the card label words. Languages: every
* language of the extension's i18n (English, Polish, German — enforced by paymentCardWords.test.js) plus the ones
* covered by Chromium's credit card autofill patterns.
*/
const paymentCardLabelDeniedWords = /* @__PURE__ */ Object.freeze([
  'gift card',
  'giftcard',
  'gift certificate',
  'gift voucher',
  'voucher',
  'coupon',
  'promo code',
  'promotion code',
  'promotional code',
  'discount code',
  'loyalty',
  'frequent flyer',
  'membership',
  'member number',
  'iban',
  'bank account',
  'account number',
  'routing number',
  'one-time',
  'one time',
  'otp',
  '2fa',
  'sms',
  'text message',
  'sent to',
  'passport',
  'document number',
  'phone',
  'mobile',
  'birth',
  'birthdate',
  'birthday',
  'registration number',
  'tax',
  'sim',
  'reward',
  'rewards',
  'club',
  'bonus',
  'points',
  'id card',
  'identity',
  'library',
  'student',
  'insurance',
  'health',
  'transit',
  'authenticator',
  'emailed',
  'texted',
  'we sent',
  'sent you',
  'geschenkkarte',
  'geschenkgutschein',
  'gutschein',
  'kundenkarte',
  'kundennummer',
  'mitgliedsnummer',
  'kontonummer',
  'bankleitzahl',
  'telefon',
  'handy',
  'mobilnummer',
  'geburtsdatum',
  'steuernummer',
  'versicher',
  'ausweis',
  'bibliothek',
  'bonuskarte',
  'clubkarte',
  'mitglied',
  'podarunkow',
  'rabatow',
  'promocyjn',
  'kupon',
  'lojalnościow',
  'członkowsk',
  'jednorazow',
  'numer konta',
  'numeru konta',
  'data urodzenia',
  'pesel',
  'nip',
  'osobist',
  'paszport',
  'klubowa',
  'klubowe',
  'klubowy',
  'stałego klienta',
  'dużej rodziny',
  'legitymac',
  'ubezpiecz',
  'biblioteczn',
  'studenck',
  'bonusow',
  'tarjeta regalo',
  'tarjeta de regalo',
  'cupón',
  'cupon',
  'código promocional',
  'documento',
  'teléfono',
  'telefono',
  'fecha de nacimiento',
  'pasaporte',
  'carte cadeau',
  'carte-cadeau',
  'code promo',
  'passeport',
  'téléphone',
  'telephone',
  'date de naissance',
  'réservation',
  'reservation',
  'carta regalo',
  'buono regalo',
  'codice promozionale',
  'codice sconto',
  'data di nascita',
  'passaporto',
  'cartão presente',
  'cartao presente',
  'vale-presente',
  'cupom',
  'cpf',
  'cnpj',
  'telefone',
  'celular',
  'data de nascimento',
  'passaporte',
  'подарочн',
  'промокод',
  'телефон',
  'дата рождения',
  'паспорт',
  'ギフトカード',
  'ギフト券',
  'クーポン',
  'ポイントカード',
  '会員番号',
  '電話',
  '生年月日',
  'パスポート',
  '礼品卡',
  '禮品卡',
  '会员',
  '會員',
  '优惠券',
  '優惠券',
  '电话',
  '手机',
  '手機',
  '生日',
  '护照',
  '護照',
  '기프트카드',
  '기프트 카드',
  '상품권',
  '쿠폰',
  '멤버십',
  '전화',
  '휴대폰',
  '생년월일',
  '여권',
  'kartu hadiah',
  'telepon',
  'tanggal lahir',
  'paspor'
]);

export default paymentCardLabelDeniedWords;
