// SPDX-License-Identifier: BUSL-1.1
//
// Copyright © 2025 Two Factor Authentication Service, Inc.
// Licensed under the Business Source License 1.1
// See LICENSE file for full terms

const personalInfoDeniedKeywords = Object.freeze([
  // --- First name ---
  'firstname',
  'first_name',
  'first-name',
  'givenname',
  'given_name',
  'given-name',
  'fname',
  'vorname',
  'prenom',
  'voornaam',
  'imie',
  'fornamn',
  'fornavn',
  'etunimi',
  'keresztnev',
  'prenume',
  'primeiro_nome',
  'primer_nombre',
  'primo_nome',
  'krestni',
  'adiniz',
  'priimek_ime',
  'shimei',
  'xingming',
  'ireum',
  'ho_ten',

  // --- Last name ---
  'lastname',
  'last_name',
  'last-name',
  'familyname',
  'family_name',
  'family-name',
  'surname',
  'lname',
  'nachname',
  'familienname',
  'nom_famille',
  'nom_de_famille',
  'achternaam',
  'nazwisko',
  'efternamn',
  'efternavn',
  'sukunimi',
  'vezeteknev',
  'csaladnev',
  'apellido',
  'apellidos',
  'cognome',
  'sobrenome',
  'prijmeni',
  'priezvisko',
  'prezime',
  'priimek',
  'soyadi',
  'soyad',
  'familia_name',

  // --- Middle name ---
  'middlename',
  'middle_name',
  'middle-name',
  'mname',
  'segundo_nombre',
  'deuxieme_prenom',
  'zweitname',
  'secondname',
  'second_name',
  'second-name',

  // --- Full name ---
  'fullname',
  'full_name',
  'full-name',
  'realname',
  'real_name',
  'real-name',
  'truename',
  'true_name',
  'true-name',
  'ho_va_ten',

  // --- Maiden name ---
  'maidenname',
  'maiden_name',
  'maiden-name',

  // --- Birthday ---
  'birthday',
  'birthdate',
  'birth_date',
  'birth-date',
  'dateofbirth',
  'date_of_birth',
  'date-of-birth',
  'bday',
  'birthyear',
  'birth_year',
  'birth-year',
  'birthmonth',
  'birth_month',
  'birth-month',
  'birthday_day',
  'birthday_month',
  'birthday_year',
  'geburtsdatum',
  'geburtstag',
  'date_naissance',
  'date_de_naissance',
  'datedenaissance',
  'fecha_nacimiento',
  'fecha_de_nacimiento',
  'fechanacimiento',
  'data_nascita',
  'data_di_nascita',
  'datanascita',
  'data_nascimento',
  'data_de_nascimento',
  'datanascimento',
  'geboortedatum',
  'data_urodzenia',
  'dataurodzenia',
  'datum_narozeni',
  'datumnarozeni',
  'datum_narodenia',
  'fodelsedatum',
  'fodselsdag',
  'syntymaaika',
  'syntymapaiva',
  'szuletesi',
  'szuletesnap',
  'data_nasterii',
  'datanasterii',
  'rojstni_datum',
  'datum_rodjenja',
  'datumrodjenja',
  'dogum_tarihi',
  'dogumtarihi',
  'tanjoubi',
  'seinengappi',
  'shengri',
  'ngay_sinh',

  // --- Gender ---
  'gender'
]);

export default personalInfoDeniedKeywords;
