// SPDX-License-Identifier: BUSL-1.1
//
// Copyright © 2025 Two Factor Authentication Service, Inc.
// Licensed under the Business Source License 1.1
// See LICENSE file for full terms

const userNameWords = /* @__PURE__ */ Object.freeze([
  // user / username
  'user',
  'username',
  'përdorues',
  'erabiltzailea',
  'карыстальнік',
  'korisnik',
  'потребител',
  'usuari',
  'utilizatore',
  'korisnik',
  'uživatel',
  'bruger',
  'gebruiker',
  'kasutaja',
  'käyttäjä',
  'utilisateur',
  'brûker',
  'benutzer',
  'Benutzer',
  'χρήστης',
  'felhasználó',
  'Notandi',
  'úsáideoir',
  'utente',
  'lietotājs',
  'Vartotojas',
  'Benotzer',
  'корисник',
  'utent',
  'bruker',
  'użytkownik',
  'do utilizador',
  'utilizator',
  'пользователь',
  'cleachdaiche',
  'корисник',
  'užívateľ',
  'uporabnik',
  'usuario',
  'användare',
  'кулланучы',
  'користувача',
  'defnyddiwr',
  'באַניצער',
  'օգտագործող',
  'istifadəçi',
  'ব্যবহারকারী',
  '用户',
  '用戶',
  'მომხმარებელი',
  'વપરાશકર્તા',
  'उपयोगकर्ता',
  'neeg siv',
  'ユーザー',
  'ಬಳಕೆದಾರ',
  'пайдаланушы',
  'អ្នក​ប្រើ',
  '사용자',
  'колдонуучу',
  'ຜູ້ໃຊ້',
  'ഉപയോക്താവ്',
  'वापरकर्ता',
  'хэрэглэгч',
  'အသုံးပြုသူကို',
  'प्रयोगकर्ता',
  'ଉପଯୋଗକର୍ତ୍ତା',
  'کارن',
  'ਉਪਭੋਗਤਾ',
  'استعمال ڪندڙ',
  'පරිශීලක',
  'корбар',
  'பயனர்',
  'వినియోగదారు',
  'ผู้ใช้',
  'kullanıcı',
  'ulanyjy',
  'صارف',
  'ئىشلەتكۈچى',
  'foydalanuvchi',
  'người dùng',
  'مستخدم',
  'מִשׁתַמֵשׁ',
  'bikaranîvan',
  'کاربر',
  'gebruiker',
  'mosebedisi',
  'isticmaale',
  'mtumiaji',
  'umsebenzisi',
  'gumagamit',
  'mea hoʻohana',
  'Pengguna',
  'panganggo',
  'mpampiasa',
  'pengguna',
  'kaiwhakamahi',
  'tagata fa\'aoga', // Samoan
  'pamaké',
  'uzanto',
  'itilizatè',
  // login
  'login',
  'log-in',
  'signin',
  'sign-in',
  'signup',
  'sign-up',
  // identifier / credential / identity
  'identifier',
  'credential',
  'identity',
  // email
  'email',
  'e-mail'
]);

export default userNameWords;
