// SPDX-License-Identifier: BUSL-1.1
//
// Copyright © 2025 Two Factor Authentication Service, Inc.
// Licensed under the Business Source License 1.1
// See LICENSE file for full terms

// camelCase - other cases are generated in paymentCardSecurityCodeSelectors.js
const paymentCardSecurityCodeTexts = /* @__PURE__ */ Object.freeze([
  'ccCsc',
  'cc-Csc',
  'cc_Csc',
  'cc-csc',
  'cc_csc',
  'ccCvv',
  'cc-Cvv',
  'cc_Cvv',
  'cc-cvv',
  'cc_cvv',
  'ccCvc',
  'cc-Cvc',
  'cc_Cvc',
  'cc-cvc',
  'cc_cvc',
  'csc',
  'cvv',
  'cvc',
  'ccv',
  'cvn',
  'cid',
  'securityCode',
  'security-Code',
  'security_Code',
  'security-code',
  'security_code',
  'cardSecurityCode',
  'card-Security-Code',
  'card_Security_Code',
  'card-security-code',
  'card_security_code',
  'cardCvc',
  'card-Cvc',
  'card_Cvc',
  'card-cvc',
  'card_cvc',
  'cardCvv',
  'card-Cvv',
  'card_Cvv',
  'card-cvv',
  'card_cvv',
  'cardVerification',
  'card-Verification',
  'card_Verification',
  'card-verification',
  'card_verification',
  'cardVerificationCode',
  'card-Verification-Code',
  'card_Verification_Code',
  'card-verification-code',
  'card_verification_code',
  'cardVerificationValue',
  'card-Verification-Value',
  'card_Verification_Value',
  'card-verification-value',
  'card_verification_value',
  'secCode',
  'sec-Code',
  'sec_Code',
  'sec-code',
  'sec_code',
  'cvv2',
  'cvc2',
  'cid2',
  'xCardCode',
  'x-Card-Code',
  'x_Card_Code',
  'x-card-code',
  'x_card_code'
]);

export default paymentCardSecurityCodeTexts;
