// SPDX-License-Identifier: BUSL-1.1
//
// Copyright © 2025 Two Factor Authentication Service, Inc.
// Licensed under the Business Source License 1.1
// See LICENSE file for full terms

export default [
  { url: 'https://logon.vanguard.com/logon', name: 'Vanguard' },
  { url: 'https://accounts.google.com/signin', name: 'Google', expect: { username: true, password: false } },
  { url: 'https://github.com/login', name: 'GitHub' },
  { url: 'https://my.statefarm.com/', name: 'StateFarm', expect: { username: true, password: false } },
  { url: 'https://appstoreconnect.apple.com/login', name: 'AppStore Connect', expect: { username: true, password: false } },
  { url: 'https://www.ifirma.pl/app', name: 'iFirma' },
  { url: 'https://allegro.pl/logowanie', name: 'Allegro' },
  { url: 'https://www.facebook.com/', name: 'Facebook' },
  { url: 'https://www.instagram.com/', name: 'Instagram' },
  { url: 'https://pl.shein.com/user/auth/login?direction=nav', name: 'Shein', expect: { username: true, password: false } },
  { url: 'https://account.proton.me/login', name: 'Proton' },
  { url: 'https://accounts.adafruit.com/users/sign_in', name: 'Adafruit' },
  { url: 'https://www.epicgames.com/id/login', name: 'Epic Games', expect: { username: true, password: false } },
  { url: 'https://www.reddit.com/login/', name: 'Reddit' },
  { url: 'https://accounts.toggl.com/track/login/', name: 'Toggl Track' },
  { url: 'https://accounts.zoho.eu/signin', name: 'Zoho', expect: { username: true, password: false } },
  { url: 'https://www.namecheap.com/myaccount/login/?ReturnUrl=%2f', name: 'Namecheap' },
  { url: 'https://x.com/', name: 'X', expect: { username: true, password: false } },
  { url: 'https://account.digiboox.app/index/login', name: 'Digiboox' },
  { url: 'https://login.sendgrid.com/login/password', name: 'SendGrid' },
  { url: 'https://app.simplelogin.io/auth/login', name: 'SimpleLogin' },
  { url: 'https://login.arduino.cc/login', name: 'Arduino' },
  { url: 'https://auth.opera.com/account/authenticate/email', name: 'Opera', expect: { username: true, password: false } },
  { url: 'https://auth.tuya.com/', name: 'Tuya' },
  { url: 'https://eu-north-1.signin.aws.amazon.com/', name: 'AWS Console' },
  { url: 'https://id.atlassian.com/login', name: 'Atlassian', expect: { username: true, password: false } },
  { url: 'https://app.brand24.com/user/login/', name: 'Brand24' },
  { url: 'https://www.browserstack.com/users/sign_in', name: 'BrowserStack' },
  { url: 'https://www.banggood.com/login.html', name: 'Banggood' },
  { url: 'https://dash.cloudflare.com/login', name: 'Cloudflare' },
  { url: 'https://codepen.io/login', name: 'CodePen' },
  { url: 'https://collecthw.com/auth/login', name: 'CollectHW' },
  { url: 'https://cults3d.com/en/users/sign-in', name: 'Cults3D' },
  { url: 'https://dashboard.ngrok.com/login', name: 'ngrok' },
  { url: 'https://login.microsoftonline.com/', name: 'Microsoft Online', expect: { username: true, password: false } },
  { url: 'https://cloud.digitalocean.com/login', name: 'DigitalOcean' },
  { url: 'https://discord.com/login', name: 'Discord' },
  { url: 'https://disqus.com/profile/login/', name: 'Disqus' },
  { url: 'https://dribbble.com/session/new', name: 'Dribbble', expect: { username: true, password: false } },
  { url: 'https://jsfiddle.net/user/login/', name: 'JSFiddle' },
  { url: 'https://accounts.craigslist.org/login?rp=%2Flogin%2Fhome&rt=L', name: 'Craigslist' },
  { url: 'https://auth.hbomax.com/login', name: 'HBO Max', expect: { username: true, password: false } },
  { url: 'https://www.disneyplus.com/en-gb/identity/login/enter-email', name: 'Disney+', expect: { username: true, password: false } },
  { url: 'https://www.netflix.com/pl/login', name: 'Netflix', expect: { username: true, password: false } },
  { url: 'https://store.steampowered.com/login/', name: 'Steam' },
  { url: 'https://home.openweathermap.org/users/sign_in', name: 'OpenWeatherMap' },
  { url: 'https://login.docker.com/u/login/identifier', name: 'Docker', expect: { username: true, password: false } },
  { url: 'https://ifttt.com/login', name: 'IFTTT' },
  { url: 'https://login.gog.com/auth', name: 'GOG.com' },
  { url: 'https://stackoverflow.com/users/login', name: 'Stack Overflow' },
  { url: 'https://dashboard.stripe.com/login', name: 'Stripe' },
  { url: 'http://tmcc.instructure.com/', name: 'Instructure' },
  { url: 'https://www.samsclub.com/login?vid=oaoh&tid=0&returnUrl=%2F', name: 'Sam\'s Club', expect: { username: true, password: false } },
];
